### ISSUE TITLE
Unable to install lsdo_geo

### ISSUE THREAD

**Issue by darshansarojini** [LSDOlab/lsdo_geo#1]
I get the following when trying to install lsdo_geo on Ubuntu 22.04 (through WSL2)

**Successfully installed cython**
pip install cython
Collecting cython
  Obtaining dependency information for cython from https://files.pythonhosted.org/packages/15/37/314c82797f3798d738f5bde4b85c01f54b2b81acf516fb3fcbc6896c5f8f/Cython-3.0.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Downloading Cython-3.0.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.1 kB)
Downloading Cython-3.0.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 982.6 kB/s eta 0:00:00
Installing collected packages: cython
Successfully installed cython-3.0.0

**Trying to install lsdo_geo**
(LsdoSciTech2024) sdarshan@DESKTOP-KN91LB2:~/Lsdo/SciTech2024/lsdo_geo$ pip3 install -e .
Obtaining file:///home/sdarshan/Lsdo/SciTech2024/lsdo_geo
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      /home/sdarshan/anaconda3/envs/LsdoSciTech2024/lib/python3.9/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /home/sdarshan/Lsdo/SciTech2024/lsdo_geo/lsdo_geo/cython/get_open_uniform.pxd
        tree = Parsing.p_module(s, pxd, full_module_name)
      Compiling lsdo_geo/cython/get_open_uniform.pyx because it changed.
      [1/1] Cythonizing lsdo_geo/cython/get_open_uniform.pyx
      /home/sdarshan/anaconda3/envs/LsdoSciTech2024/lib/python3.9/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /home/sdarshan/Lsdo/SciTech2024/lsdo_geo/lsdo_geo/cython/get_open_uniform_py.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      warning: lsdo_geo/cython/get_open_uniform_py.pyx:6:0: Overriding cdef method with def method.

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      import numpy as np
      cimport numpy as np

      from lsdo_geo.cython.get_open_uniform cimport get_open_uniform

      def get_open_uniform(int order, int num_control_points, np.ndarray[double] knot_vector):
      ^
      ------------------------------------------------------------

      lsdo_geo/cython/get_open_uniform_py.pyx:6:0: Assignment to non-lvalue 'get_open_uniform'
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/sdarshan/Lsdo/SciTech2024/lsdo_geo/setup.py", line 46, in <module>
          ext_modules = ext_modules + cythonize(
        File "/home/sdarshan/anaconda3/envs/LsdoSciTech2024/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1134, in cythonize
          cythonize_one(*args)
        File "/home/sdarshan/anaconda3/envs/LsdoSciTech2024/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1301, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: lsdo_geo/cython/get_open_uniform_py.pyx
      Compiling lsdo_geo/cython/get_open_uniform_py.pyx because it changed.
      [1/1] Cythonizing lsdo_geo/cython/get_open_uniform_py.pyx
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by afletche** [comment]
The newest version of Cython doesn't work for the code. If you get an error like this, try installing Cython version 0.29.28. If that doesn't work, try deleting all the .so files
